server {
   
    set $api_domain $API_DOMAIN;
    set $bhuvan_domain $BHUVAN_DOMAIN;
    set $fonts_domain $FONTS_DOMAIN;
    set $fonts_static_domain $FONTS_STATIC_DOMAIN;
    set $osm_domain $OSM_DOMAIN;

    listen 80;

    # Root directory for your app
    root /usr/share/nginx/html;
    index index.html;

    # Default server name
    server_name _;

    # Serve React App (SPA)
    location / {
        try_files $uri /index.html;
    }

    # Serve static files with proper caching
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|woff|woff2|ttf|svg|eot)$ {
        expires 1y;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    # Deny access to sensitive files
    location ~* \.(env|json|log|git|sql)$ {
        deny all;
    }

    # Security headers with CSP using variables
    add_header Content-Security-Policy "
        default-src 'self';
        style-src 'self' $fonts_domain 'unsafe-inline';
        font-src 'self' $fonts_static_domain;
        connect-src 'self' $api_domain $bhuvan_domain/bhuvan/gwc/service/wms $osm_domain/;
        media-src 'self' $api_domain/;
        img-src 'self' data: $api_domain/ $bhuvan_domain/ $fonts_static_domain/ $osm_domain/;
        script-src 'self' 'unsafe-inline' 'unsafe-eval';
    " always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Error handling
    error_page 404 /index.html;

    # Logs for debugging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}