version: '3.3' 
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REACT_APP_BASE_URL=https://api.gromed.in/
      - REACT_APP_BHUVAN_URL=https://bhuvan-vec1.nrsc.gov.in
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped