export const dashboardInitialState = {
  userInfo: {
    dealer: 0,
    manufacturer: 0,
    dto: 0,
    owner: 0,
  },
  fitmentInfo: {
    fitted: 0,
    onlineDevice: 0,
    offlineDevice: 0,
  },
  dealerFitmentInfo: {
    total: 0,
    monthly: 0,
    daily: 0,
  },
  dealerDeviceInfo: {
    assigned: 0,
    returned: 0,
    stocked: 0,
    faulty: 0,
  },
  eSIMInfo: {
    totalActivation: 0,
    oneYearRenewal: 0,
    twoYearRenewal: 0,
  },
  deviceStatusInfo: {
    online: 0,
    todayOffline: 0,
    sevenDaysOffline: 0,
    thirtyDaysOffline: 0,
  },
  deviceHealthInfo: {
    totalActivatedDevice: 0,
    todayActive: 0,
    inActiveFor7Days: 0,
    inActiveFor30Days: 0,
  },
  alertInfo: {
    totalAlert: 0,
    thisMonthAlert: 0,
    todayAlert: 0,
  },
  miscInfo: {
    dealer: 0,
    allocated: 0,
    activation: 0,
    expired: 0,
  },
  modelInfo: {
    model: 0,
    m2mLinked: 0,
  },
  userDashboardInfo: {
    deviceActivated: 0,
    vehicles: 0,
    onlineDevice: 0,
    offlineDevice: 0,
    sevenDaysOffline: 0,
    thirtyDaysOffline: 0,
    alert: 0,
    monthlyAlert: 0,
    dailyAlert: 0,
    harshBreaking: 0,
    suddenTurn: 0,
    overSpeeding: 0,
    sosCalls: 0,
    genuineCalls: 0,
    fakeCalls: 0,
  },
  userInfoForAdmin: {
    stateUser: 0,
    eSimUser: 0,
    manufacturer: 0,
    sosAdmin: 0,
  },
  stateInfo: {
    total: 0,
    active: 0,
    inactive: 0,
  },
  adminFitmentInfo: {
    fitted:0,
    toggedDevice:0,
    onlineDevice: 0,
    offlineDevice: 0,
  },
};