name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start &

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Install forever
      run: npm install -g forever      
    - name: Change directory
      run: cd /var/www/html/actions-runner/_work/skytronfrontend/skytronfrontend
    - name: Restart NodeJS Service
      run: |
        # Assuming "forever" is installed globally
        forever stopall
        forever start npm start &
